// USER
export const USER = {
  CREATING: "USER_CREATING",
  CREATED: "USER_CREATED",
  CREATION_FAILED: "USER_CREATION_FAILED",
  UPDATING: "USER_UPDATING",
  UPDATED: "USER_UPDATED",
  UPDATE_FAILED: "USER_UPDATE_FAILED",
  AUTHENTICATING: "AUTHENTICATING",
  AUTHENTICATED: "AUTHENTICATED",
  AUTHENTICATION_FAILED: "AUTHENTICATION_FAILED",
  PROFILE_LOADED: "PROFILE_LOADED",
  PASSWORD_RESET_REQUEST_SENT: "PASSWORD_RESET_REQUEST_SENT",
  PASSWORD_RESET_SUCCESSFUL: "PASSWORD_RESET_SUCCESSFUL",
  DATA_FETCHED: "USER_DATA_FETCHED",
  LIST_FETCHED: "USERS_LIST_FETCHED",
  USER_WORK_SAVED: "USER_WORK_SAVED",
  USER_WORK_UPDATED: "USER_WORK_UPDATED",
  USER_WORK_DATA_FETCHED: "USER_WORK_DATA_FETCHED",
  USER_WORK_SELECTED_FETCHED: "USER_WORK_SELECTED_FETCHED",
  SELECTED_USER_DATA_FETCHED: "SELECTED_USER_DATA_FETCHED",
  SELECTED_USER_WORK_DATA_FETCHED: "SELECTED_USER_WORK_DATA_FETCHED",
  ACTION_SUCCESSFUL: "USER_ACTION_SUCCESSFUL",
  START_ACTION: "START_ACTION",
  UPLOAD_IMAGE: "USER_UPLOAD_IMAGE",
  SIGN_OUT: "USER_SIGN_OUT",
};

// MESSAGES
export const MESSAGES = {
  FETCHING: "MESSAGES_FETCHING",
  FETCHED: "MESSAGES_FETCHED",
  ADD: "MESSAGES_ADD_NEW",
  UPDATE: "MESSAGES_UPDATE",
  CREATION_FAILED: "MESSAGES_CREATION_FAILED",
  UPDATE_FAILED: "MESSAGES_UPDATE_FAILED",
  SAVED: "MESSAGES_SAVED",
};

// MESSAGES
export const QUESTIONS = {
  FETCHING: "QUESTIONS_FETCHING",
  FETCHED: "QUESTIONS_FETCHED",
  ADD: "QUESTIONS_ADD_NEW",
  UPDATE: "QUESTIONS_UPDATE",
  CREATION_FAILED: "QUESTIONS_CREATION_FAILED",
  UPDATE_FAILED: "QUESTIONS_UPDATE_FAILED",
  SAVED: "QUESTIONS_SAVED",
};

export const LAYOUT = {
  SIDE_BAR_COLLAPSE_STATE_CHANGED: "SIDE_BAR_COLLAPSE_STATE_CHANGED",
};
